WTF_CSRF_ENABLED = True
SECRET_KEY = 'everythingshedoesismagic'

TUMBLR_API = "m9uA4qk2gTN8P92aLTPZQCUZ1IajGMyLSuzfrzXqAwvUVsgfXB"
TUMBLR_SECRET = "gu9pZj2OH8KqiXuejycZ8CsVl6oTdn9UBGkLcN54qbWjuxO2LH"
TUMBLR_OAUTH =  "cSF8rIHQjsN3vPx4zzZHLpaSwEFYK3RXBloI3CRJcpjlwDyhZm"
TUMBLR_SECRET2 = "AGIZPKf6cnJRCGnZtGzM1lzVxotDT7ogcraeF7d7VM6Ngo23By"